version: '2'

services:
  mirth-connect:
    build: mirth-connect
    volumes:
      - "./mirth-connect/mirth.properties:/opt/mirth-connect/conf/mirth.properties:ro"
      - "./data/spools/:/var/spool/mirth/:rw"
    ports: 
      - "8080:8080"
      - "8443:8443"
    links:
      - db
    depends_on:
      - db